# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Things I don't want to publish to github
[[ -s "$HOME/.secrets" ]] && source "$HOME/.secrets"

# Give me my bash style incremental search
bindkey '^R' history-incremental-search-backward

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias show_hidden="defaults write com.apple.finder AppleShowAllFiles TRUE && killall Finder"
alias hide_hidden="defaults write com.apple.finder AppleShowAllFiles FALSE && killall Finder"
alias bower='noglob bower'

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rails brew bundler docker npm zeus vagrant)

source $ZSH/oh-my-zsh.sh

# PATH='/desired/path/here:and/even/more/here/'
export PATH=/usr/local/bin:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

# Per directory ack settings
# export ACKRC=”.ackrc”

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi # enable shims and autocompletion for rbenv

### Added by the Heroku Toolbelt
export PATH="$PATH:/usr/local/heroku/bin"

# # Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Postgres
export PGHOST=localhost

# Postgres App
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin"

# npm bin
export PATH="$PATH:./node_modules/.bin"

# Bundle open gem
export BUNDLER_EDITOR=mvim

# JAVA SDK
export JAVA_HOME=$(/usr/libexec/java_home)

# rails 4 secret key for production
export SECRET_KEY_BASE='5ca4aafaf356e2961b81e67fa69bea64e7be87d75c0aec8e1bf15b8abf1edf019e791b535eb338f0f99f0fc0d5969dff0963dd5e370706b5471619981f2a0dc7'

# Quoine
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export NVM_DIR="/Users/huynh/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export DOCKER_HOST='tcp://192.168.59.103:2375'
